CREATE TABLE `convocatorias` (
	`id` text PRIMARY KEY NOT NULL,
	`community_id` text,
	`tipo` text NOT NULL DEFAULT 'Ordinaria',
	`ciudad` text DEFAULT '',
	`fecha_carta` text NOT NULL,
	`fecha_junta` text NOT NULL,
	`horas_primera` text NOT NULL DEFAULT '18:30',
	`horas_segunda` text NOT NULL DEFAULT '19:00',
	`lugar` text DEFAULT 'Portal del edificio',
	`presidente_nombre` text,
	`agenda_items` text,
	`morosos_list` text,
	`morosos_fecha` text,
	`presupuesto` text,
	`estado_cuentas` text,
	`incluir_delegacion` integer DEFAULT 1,
	`incluir_morosos` integer DEFAULT 1,
	`incluir_presupuesto` integer DEFAULT 0,
	`incluir_estado_cuentas` integer DEFAULT 0,
	`content` text,
	`status` text DEFAULT 'draft',
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`community_id`) REFERENCES `communities`(`id`) ON UPDATE no action ON DELETE cascade
);
